# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :build_and_export do
 # add actions here: https://docs.fastlane.tools/actions
    increment_build_number(
      xcodeproj: "CatsListView.xcodeproj",
      build_number: "1.1"
    )

    gym

    firebase_app_distribution(
      app: "CatsListView",
      testers: "o.frankiv@ukma.edu.ua",
      release_notes: "Release notes for version 1.1"
    )

    puts "Everything worked!"
  end


  lane :take_screenshots do
    snapshot
  end

  lane :bitrise do
     # Check if the branch is a release branch
        
          # Run necessary build and distribution steps
    increment_build_number(
      xcodeproj: "CatsListView.xcodeproj",
      build_number: "1.2"
    )
          
    gym
          
          
          # Output success message
    puts "Automatic build completed successfully!"
        
  end 
      
end